version: 2
updates:
  # Keep Docker dependencies up-to-date
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"

  # Keep GitHub Actions up-to-date
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
