---
image: gitpod/workspace-full:latest

tasks:
  - name: install-slow-packages
    before: make install-slow-packages
    init: graphite repo init --trunk=master
    command: exit
  - name: graphite-setup
    init: gt
    command: exit
  - command: tmux

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: true
