---
image: gitpod/workspace-full:latest

tasks:
  - command: /workspace/dotfiles/start-tmux-and-install-slow-packages.sh

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    # add a check to pull requests (defaults to true)
    addCheck: true
