image: topher200/dotfiles:latest

tasks:
  - command: |
      sudo cp /home/gitpod/.gitconfig /etc/gitconfig
      sudo su - topher
      tmux new-sess -A -s dev
      cd dotfiles

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: true
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: true
