exclude: |
  (?x)^(
      files/.config/nvim/pack.*|
      files/.oh-my-zsh/.*|
      files/.tmux/plugins/.*|
      files/.zshenv|
      files/bin/dropbox_uploader.sh|
      files/bin/ftwind|
      files/bin/run-forever.sh|
      files/bin/vimv|
      files/condarc|
      files/zsh-custom/.*
  )$

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-added-large-files # Prevent giant files from being committed
      - id: check-case-conflict # Check for files that would conflict in case-insensitive filesystems
      - id: check-executables-have-shebangs # Ensures that (non-binary) executables have a shebang.
      - id: check-json # This hook checks json files for parseable syntax.
      - id: check-yaml # This hook checks yaml files for parseable syntax.
      - id: end-of-file-fixer # Ensures that a file is either empty, or ends with one newline.
      - id: trailing-whitespace # This hook trims trailing whitespace.

  - repo: https://github.com/AleksaC/circleci-cli-py
    rev: v0.1.16535
    hooks:
      - id: circle-ci-validator
        files: \.circleci/.*\.yml$

  - repo: local
    hooks:
      - id: prettier
        name: prettier
        entry: prettier
        language: system
        args: [--write]
        files: \.(js|ts|jsx|tsx|css|less|html|json|markdown|md|yaml|yml)$

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: "2.1.5"
    hooks:
      - id: shellcheck
      - id: shfmt

  - repo: https://github.com/sirosen/check-jsonschema
    rev: 0.10.2
    hooks:
      - id: check-github-actions
      - id: check-github-workflows
