---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.2.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
          - id: check-added-large-files
    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.0.11 # or specific tag
      hooks:
          - id: yamlfmt
    - repo: https://github.com/syntaqx/git-hooks
      rev: v0.0.17
      hooks:
          - id: circleci-config-validate
          - id: shellcheck
          - id: shfmt

exclude: |
    (?x)^(
        files/zsh-custom/.*|
        files/.emacs.d/.*|
        files/.oh-my-zsh/.*
    )$
