exclude: |
  (?x)^(
      files/zsh-custom/.*|
      files/.emacs.d/.*|
      files/.oh-my-zsh/.*
  )$

# repos:
#   - repo: https://github.com/syntaqx/git-hooks
#     rev: v0.0.17
#     hooks:
#       # TODO: this breaks a lot of things, need to fix
#       # - id: shellcheck
#       # TODO: install shfmt binary package to unlock this hook
#       # - id: shfmt

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-added-large-files # Prevent giant files from being committed
      - id: check-case-conflict # Check for files that would conflict in case-insensitive filesystems
      - id: check-executables-have-shebangs # Ensures that (non-binary) executables have a shebang.
      - id: check-json # This hook checks json files for parseable syntax.
      - id: check-yaml # This hook checks yaml files for parseable syntax.
      - id: end-of-file-fixer # Ensures that a file is either empty, or ends with one newline.
      - id: trailing-whitespace # This hook trims trailing whitespace.

  - repo: https://github.com/AleksaC/circleci-cli-py
    rev: v0.1.16535
    hooks:
      - id: circle-ci-validator
        files: \.circleci/.*\.yml$

  - repo: local
    hooks:
      - id: prettier
        name: prettier
        entry: prettier
        language: system
        args: [--write]
        files: \.(js|ts|jsx|tsx|css|less|html|json|markdown|md|yaml|yml)$
