[[snippets]]
  description = "aws1 readonly db"
  command = "export PGPASSWORD='***REMOVED***'; psql -U tbrown -h readonly.aws1.wordstream.com -d adwords"
  output = ""

[[snippets]]
  description = "migrate all databases"
  command = "cd /Users/t.brown/dev/wordstream/server/wordstream/src && python migrate_db.py upgrade --all ; cd /Users/t.brown/dev/wordstream"
  output = ""

[[snippets]]
  description = "install all dependencies"
  command = "wow && cd /Users/t.brown/dev/wordstream && python dependencies.py install dependencies.txt; python dependencies.py install dependencies-dev.txt; python dependencies.py install dependencies-ws.txt"
  output = ""

[[snippets]]
  description = "post review to reviewboard"
  command = "cd /Users/t.brown/dev/wordstream/ && python -u utils/review.py && git push origin HEAD"
  output = ""

[[snippets]]
  description = "post review to reviewboard tracking branch"
  command = "cd /Users/t.brown/dev/wordstream/ && python -u utils/review.py --tracking-branch FIX_ME && git push origin HEAD"
  output = ""

[[snippets]]
  description = "kill wordstream servers"
  command = "kill-servers.sh"
  output = ""

[[snippets]]
  description = "ssh into dev box aws buildbot"
  command = "ssh dev-aws-two"
  output = ""

[[snippets]]
  description = "download reports"
  command = "wow ; cd /Users/t.brown/dev/wordstream/server/wordstream/src ; python -u update.py download_adwords_reports -c conf & ; python download_bing_ads_reports.py conf/ 1 & ; python download_facebook_reports.py conf & ; python download_facebook_leads.py conf & ; cd /Users/t.brown/dev/wordstream"
  output = ""

[[snippets]]
  description = "sig kill emacs"
  command = "pkill -SIGUSR2 Emacs"
  output = ""

[[snippets]]
  description = "weather Boston"
  command = "curl wttr.in/~Boston"
  output = ""

[[snippets]]
  description = "ssh tracebacks prod"
  command = "ssh -i ~/.ssh/tbrown-sandbox.pem ec2-user@tracebacks.wordstream-sandbox.com"
  output = ""

[[snippets]]
  description = "what's my ip"
  command = "curl ipinfo.io/ip"
  output = ""

[[snippets]]
  description = "ssh wordy"
  command = "ssh t.brown@wordy.wordstream-sandbox.com"
  output = ""

[[snippets]]
  description = "cluster readonly db"
  command = "export PGPASSWORD='***REMOVED***'; psql -U tbrown -h readonly.cluster.wordstream.com -d wordstream"
  output = ""

[[snippets]]
  description = "scrub wordstream"
  command = "cd /Users/t.brown/dev/wordstream/ ; rm -fr client/manager/src/static/gen/ ; rm -fr client/manager/src/static/.webassets-cache/ ; find . -name \"*.pyc\" -exec rm {} \\;\\n"
  output = ""

[[snippets]]
  description = "postgres logs"
  command = "less +F /usr/local/var/postgres/server.log"
  output = ""

[[snippets]]
  description = "find from root"
  command = "find / -name \"*FIX_ME*\" 2>/dev/null"
  output = ""

[[snippets]]
  description = "watchman logs"
  command = "less +F /usr/local/var/run/watchman/t.brown-state/log"
  output = ""

[[snippets]]
  description = "flush memcache (dogpile)"
  command = "echo 'flush_all' | nc localhost 11211"
  output = ""

[[snippets]]
  description = "create wordstream watchman trigger with main"
  command = "watchman -j <<< \"[\\\"trigger\\\", \\\"`pwd`\\\", {  \\\"name\\\": \\\"python-files\\\",  \\\"expression\\\": [      \\\"allof\\\",          [\\\"suffix\\\", \\\"py\\\"],          [\\\"type\\\", \\\"f\\\"],          [\\\"not\\\", [\\\"imatch\\\", \\\"flycheck*.py\\\"]],          [\\\"not\\\", [\\\"iname\\\", \\\"*.#*\\\"]],          [\\\"not\\\", [\\\"suffix\\\", \\\"pyc\\\"]]      ],  \\\"command\\\": [\\\"supervisorctl\\\", \\\"-c\\\", \\\"/Users/t.brown/dev/bin/supervisor.conf\\\", \\\"restart\\\", \\\"main:\\\"],  \\\"append_files\\\": false}]\""
  output = ""

[[snippets]]
  description = "create wordstream watchman trigger with async"
  command = "watchman -j <<< \"[\\\"trigger\\\", \\\"`pwd`\\\", {  \\\"name\\\": \\\"python-files\\\",  \\\"expression\\\": [      \\\"allof\\\",          [\\\"suffix\\\", \\\"py\\\"],          [\\\"type\\\", \\\"f\\\"],          [\\\"not\\\", [\\\"imatch\\\", \\\"flycheck*.py\\\"]],          [\\\"not\\\", [\\\"iname\\\", \\\"*.#*\\\"]],          [\\\"not\\\", [\\\"suffix\\\", \\\"pyc\\\"]]      ],  \\\"command\\\": [\\\"supervisorctl\\\", \\\"-c\\\", \\\"/Users/t.brown/dev/bin/supervisor.conf\\\", \\\"restart\\\", \\\"all\\\"],  \\\"append_files\\\": false}]\""
  output = ""

[[snippets]]
  description = "ssh staging"
  command = "ssh staging.wordstream.com"
  output = ""

[[snippets]]
  description = "copy last command"
  command = "echo \"!!\" | pbcopy"
  output = ""

[[snippets]]
  description = "clear git rerere cache"
  command = "rm -rf .git/rr-cache"
  output = ""

[[snippets]]
  description = "elastic search es proxy"
  command = "ssh -i \"tbrown-key.pem\" ec2-user@ec2-34-200-239-251.compute-1.amazonaws.com"
  output = ""

[[snippets]]
  description = "seashells broadcast online"
  command = "!! | nc seashells.io 1337"
  output = ""

[[snippets]]
  description = "kill all tmux sessions"
  command = "tmux list-sessions | cut -d: -f 1 | xargs -I {} tmux kill-session -t {}"
  output = ""

[[snippets]]
  description = "remove watchman"
  command = "watchman watch-del ~/dev/wordstream"
  output = ""

[[snippets]]
  description = "git filename changes since last commit"
  command = "git --no-pager diff --name-only HEAD^"
  output = ""

[[snippets]]
  description = "git force push branch"
  command = "force-push-branch"
  output = ""
