---
version: 2.1

jobs:
  test-lint:
    machine:
      image: ubuntu-2004:202010-01 # includes Ubuntu 20.04, docker 19.03.13, docker-compose 1.27.4

    steps:
      - checkout
      - run: sudo apt-get install shellcheck
      - run: sudo snap install shfmt
      - run: npm install --global prettier
      - run: pip3 install pre-commit
      - run: make lint
  test-full-install:
    machine:
      image: ubuntu-2004:202010-01 # includes Ubuntu 20.04, docker 19.03.13, docker-compose 1.27.4

    steps:
      - run: sudo apt update && sudo apt install -y make
      - checkout
      - run: BUILDKIT_PROGRESS=plain make test-in-docker
  test-gitpod-bootstrap:
    machine:
      image: ubuntu-2004:202010-01 # includes Ubuntu 20.04, docker 19.03.13, docker-compose 1.27.4

    steps:
      - checkout
      - run: ./bootstrap.sh
workflows:
  version: 2
  test:
    jobs:
      - test-lint
      - test-gitpod-bootstrap
      - test-full-install
