---
version: 2.1

jobs:
    test:
        machine:
            image: ubuntu-2004:202010-01 # includes Ubuntu 20.04, docker 19.03.13, docker-compose 1.27.4

        steps:
            - run: sudo apt update && sudo apt install -y make
            - checkout
            # pulling the image to prime the cache should not be necessary, but there
            # seems to be a bug with the cache-from command.
            # https://github.com/moby/buildkit/issues/1981
            # without this pull we see CI runs stop using the cache on the 'WORKDIR'
            # call in the Dockerfile.
            - run: docker pull topher200/dotfiles:latest
            - run: BUILDKIT_PROGRESS=plain make test-in-docker
workflows:
    version: 2
    build_and_test:
        jobs:
            - test
