version: 2.1
      
jobs:
  build:
      docker:
        - image: ubuntu:latest
      steps:
        - apt update && apt install make
        - checkout
        - make install
workflows:
  version: 2
  build:
    jobs:
      - build
