version: 2.1

jobs:
  build:
    docker:
      - image: ubuntu:21.10
    steps:
      # install sudo and bash: https://github.com/dwyl/learn-circleci/issues/12
      - run: apt update && apt install -y sudo
      - run: ls -al /bin/sh && sudo rm /bin/sh && sudo ln -s /bin/bash /bin/sh && ls -al /bin/sh

      - run: sudo apt install -y make
      - checkout
      - run: make install
      # Save workspace for subsequent jobs (i.e. test)
      - persist_to_workspace:
          root: .
          paths:
            - .
  test:
    docker:
      - image: ubuntu:21.10
    steps:
      # install sudo and bash: https://github.com/dwyl/learn-circleci/issues/12
      - run: apt update && apt install -y sudo
      - run: ls -al /bin/sh && sudo rm /bin/sh && sudo ln -s /bin/bash /bin/sh && ls -al /bin/sh

      # Reuse the workspace from the build job
      - attach_workspace:
          at: .
      - run: sudo apt install -y make file shellcheck
      - run: make test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
