---
version: 2.1

executors:
  ubuntu:
    machine:
      # packages here: https://discuss.circleci.com/t/linux-machine-executor-update-2022-october-q4-update/45753
      image: ubuntu-2204:2022.10.1 # Ubuntu 22.04, Docker v20.10.14, Docker Compose v2.10.2

jobs:
  test-lint:
    executor: ubuntu
    steps:
      - checkout
      - run: sudo apt update --yes
      - run: sudo apt install shellcheck
      - run: sudo apt install snapd && sudo snap install shfmt
      - run: npm install --global prettier
      - run: pip3 install pre-commit
      - run: make lint

  test-full-install:
    executor: ubuntu
    steps:
      - run: sudo apt update --yes && sudo apt install -y make
      - checkout
      - run: BUILDKIT_PROGRESS=plain make docker-build
      - run: docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
      - run: make docker-push
      - run: BUILDKIT_PROGRESS=plain make test-in-docker

  test-gitpod-bootstrap:
    executor: ubuntu
    steps:
      - checkout
      - run: ./bootstrap.sh

workflows:
  version: 2
  test:
    jobs:
      - test-lint
      - test-gitpod-bootstrap
      - test-full-install:
          context:
            - topher200-dotfiles
