version: 2.1
jobs:
  build:
      docker:
        - image: ubuntu:latest
      steps:
        - run:
            name: install make
            command: apt install make
        - run:
            command: make install
workflows:
  version: 2
  build:
    jobs:
      - build
