version: 2.1

jobs:
  test:
    docker:
      - image: ubuntu:21.10
    steps:
      - run: apt update && apt install -y make
      - checkout
      - setup_remote_docker:
        docker_layer_caching: true
      - run: make test-in-docker
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
