---
version: 2.1

jobs:
  test-fast:
    machine:
      image: ubuntu-2004:202010-01 # includes Ubuntu 20.04, docker 19.03.13, docker-compose 1.27.4

    steps:
      - checkout
      - run: make test
  test-full-install:
    machine:
      image: ubuntu-2004:202010-01 # includes Ubuntu 20.04, docker 19.03.13, docker-compose 1.27.4

    steps:
      - run: sudo apt update && sudo apt install -y make
      - checkout
      - run: BUILDKIT_PROGRESS=plain make test-in-docker
workflows:
  version: 2
  test:
    jobs:
      - test-fast
      - test-full-install
