---
version: 2.1

executors:
  ubuntu:
    docker:
      - image: cimg/base:stable-20.04 # build-essential 12.8ubuntu1.1, curl 7.68.0, docker 20.10.14, docker-compose /usr/local/bin/docker-compose Docker Compose version v2.4.1 v2.4.1, dockerize v0.6.1, git 2.36.1, jq 1.6, ubuntu 20.04.4 LTS, wget 1.20.3


jobs:
  test-lint:
    executor: ubuntu
    steps:
      - checkout
      - run: sudo apt-get install shellcheck
      - run: sudo snap install shfmt
      - run: npm install --global prettier
      - run: pip3 install pre-commit
      - run: make lint

  test-full-install:
    executor: ubuntu
    steps:
      - run: sudo apt update && sudo apt install -y make
      - checkout
      - run: BUILDKIT_PROGRESS=plain make docker-build
      - run: docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
      - run: make docker-push
      - run: BUILDKIT_PROGRESS=plain make test-in-docker

  test-gitpod-bootstrap:
    executor: ubuntu
    steps:
      - checkout
      - run: ./bootstrap.sh

workflows:
  version: 2
  test:
    jobs:
      - test-lint
      - test-gitpod-bootstrap
      - test-full-install:
          context:
            - topher200-dotfiles
