(define-key global-map (kbd "C-<tab>") 'evil-window-next)
(define-key global-map (kbd "C-S-<tab>") 'evil-window-prev)
(define-key global-map (kbd "C-s") 'save-buffer)
(define-key global-map (kbd "C-j") 'evil-scroll-down)
(define-key global-map (kbd "C-k") 'evil-scroll-up)
