#!/bin/zsh
# shellcheck shell=bash

export MEMFAULT_EMAIL=user@example.com
export MEMFAULT_PASSWORD=asdf
export MEMFAULT_ORG=acme-inc

# pyinvoke 'echo' by default. http://docs.pyinvoke.org/en/stable/concepts/configuration.html#environment-variables
export INVOKE_RUN_ECHO=1

export LOG_RAW_SQL_QUERIES=1
export REUSE_PYTEST_CONTAINERS=1

alias cam='conda deactivate && conda deactivate && conda deactivate && conda activate memfault'

if [[ "$PWD" == "/home/topher" && -d "/home/topher/memfault" ]]; then
	cd /home/topher/memfault || exit
fi

if [[ "$PWD" == "/home/topher/memfault" ]]; then
	# aws alias
	# https://www.notion.so/memfault/Platform-Tooling-5facd1d8941945c08e82a549e192885e
	alias chamberprod='aws-vault exec topher-prod -- chamber'
	export AWS_VAULT_SECRET_SERVICE_COLLECTION_NAME=login

	# terraform
	autoload -U +X bashcompinit && bashcompinit
	complete -o nospace -C /home/topher/dev/miniforge3/envs/memfault/bin/terraform terraform
fi
