#!/bin/bash

# Aliases
alias sd='stg delete'
alias sdt='stg delete --top'
alias se='stg edit --diff'
alias sfl='stg float'
alias sn='stg new'
alias spo='stg pop'
alias spoa='stg pop --all'
alias spos='stg pop spill'
alias spu='stg push'
alias sr='stg refresh'
alias sra='git add . && stg refresh'
alias sre='stg edit --diff'
alias srem='stg rebase master'
alias sreom='stg rebase origin/master'
alias srf='stg refresh --no-verify --index'
alias sri='stg rebase --interactive'
alias srpa='git add --patch && stg refresh -i'
alias srnv='stg refresh --no-verify'
alias spr='inv stg.pull-request'
alias spro='inv stg.pull-request --onto'
alias ss='stg series --description'
alias sspl='stg refresh --spill && git reset .'
alias sst='stg status'
alias stb='git checkout stgit-topher'

# create a template file with a diff
snm() {
    cat ~/.gitmessage.memfault > "$(git rev-parse --git-dir)/patchdescr.tmpl"
    echo "#------------------------------------------------" >> "$(git rev-parse --git-dir)/patchdescr.tmpl"
    echo "#---------------------------------------------------------------------" >> "$(git rev-parse --git-dir)/patchdescr.tmpl"
    echo "\n" >> "$(git rev-parse --git-dir)/patchdescr.tmpl"
    git status >> "$(git rev-parse --git-dir)/patchdescr.tmpl"
    git diff >> "$(git rev-parse --git-dir)/patchdescr.tmpl"
    stg new
    rm "$(git rev-parse --git-dir)/patchdescr.tmpl"
}

sna() {
    sn
    sr
}

snma() {
    snm
    sr
}

# Create a new *-WIP patch with all outstanding changes
swip() {
    # Add all files to index
    stg add -A
    stg rm "$(git ls-files --deleted)" 2> /dev/null

    # Save off patch names
    CUR_PATCH=$(stg top)
    WIP_PATCH="$CUR_PATCH-WIP"

    if [[ "$CUR_PATCH" == *-WIP ]]
    then
        echo "Adding changes to $WIP_PATCH"
    else
        echo "Creating and adding changes to $WIP_PATCH"
        stg new "$WIP_PATCH" -m "--wip--"
    fi

    # Add changes to patch
    stg refresh
}

# Unload the *-WIP patch and reset all changes
swipp() {
    CUR_PATCH=$(stg top)
    if [[ "$CUR_PATCH" == *-WIP ]]
    then
        stg delete "$CUR_PATCH" --spill
        git reset
    else
        echo "No WIP patch to pop"
    fi
}

# Stash local changes, then pop
spof() {
    git stash
    stg pop
    git stash pop
}

# Stash local changes, then push
spuf() {
    git stash
    stg push
    git stash pop
}
