swipe:
  3:
    left:
      command: "xdotool key alt+Right" # History forward 
      threshold: 0.5
    right:
      command: "xdotool key alt+Left" # History back
      threshold: 0.5
    up:
      command: "xdotool key ctrl+Shift+Tab"
      interval: 0.25
      threshold: 0.25
    down:
      command: "xdotool key ctrl+Tab"
      interval: 0.25
      threshold: 0.25
  4:
    left:
      command: "xdotool key ctrl+alt+Right"
    right:
      command: "xdotool key ctrl+alt+Left"
    up:
      command: "xdotool key ctrl+alt+Down"
    down:
      command: "xdotool key ctrl+alt+Up"
pinch:
  in:
    command: "xdotool key super"
  out:
    command: "xdotool key super"
    
