[[snippets]]
  description = "open vim file with fzf"
  command = "vim -o `fzf`"
  output = ""

[[snippets]]
  description = "sig kill emacs"
  command = "pkill -SIGUSR2 Emacs"
  output = ""

[[snippets]]
  description = "weather Boston"
  command = "curl wttr.in/~Boston"
  output = ""

[[snippets]]
  description = "what's my ip"
  command = "curl v4.ifconfig.co | xsel"
  output = ""

[[snippets]]
  description = "postgres logs"
  command = "less +F /usr/local/var/log/postgres.log"
  output = ""

[[snippets]]
  description = "find from root"
  command = "find / -name \"*FIX_ME*\" 2>/dev/null"
  output = ""

[[snippets]]
  description = "copy last command"
  command = "echo \"\"\"!!\"\"\" | xsel"
  output = ""

[[snippets]]
  description = "clear git rerere cache"
  command = "rm -rf .git/rr-cache"
  output = ""

[[snippets]]
  description = "kill all tmux sessions"
  command = "tmux list-sessions | cut -d: -f 1 | xargs -I {} tmux kill-session -t {}"
  output = ""

[[snippets]]
  description = "git filename changes since last commit"
  command = "git --no-pager diff --name-only HEAD^"
  output = ""

[[snippets]]
  description = "git force push branch"
  command = "force-push-branch"
  output = ""

[[snippets]]
  description = "tmux kill unattached sessions"
  command = "tmux list-sessions | grep -v attached | cut -d: -f 1 | xargs -I {} tmux kill-session -t {}"
  output = ""

[[snippets]]
  description = "list directories and their sizes, sorted and human readable"
  command = "du -h | sort -h"
  output = ""

[[snippets]]
  description = "format json from the clipboard"
  command = "pbpaste | jq . | xsel"
  output = ""

[[snippets]]
  description = "python dictionary to json"
  command = "pbpaste | xargs -0 python -c 'import ast, json, sys ; out = ast.literal_eval(sys.argv[1]) ; print json.dumps(out)' | jq . | xsel"
  output = ""

[[snippets]]
  description = "list users of port 8000"
  command = "lsof -nP -i4TCP:8000"
  output = ""

[[snippets]]
  description = "elasticsearch low disk space reset"
  command = "curl -XPUT -H \"Content-Type: application/json\" http://localhost:9200/_all/_settings -d '{\"index.blocks.read_only_allow_delete\": null}'\\n"
  output = ""

[[snippets]]
  description = "kill all running docker containers"
  command = "docker ps -q | xargs docker kill"
  output = ""

[[snippets]]
  description = "digital ocean youtube-dl seedbox"
  command = "ssh ***REMOVED***"
  output = ""

[[snippets]]
  description = "hg diff less with color"
  command = "hg d --color on | less"
  output = ""

[[snippets]]
  description = "ssh topher personal GCP dev environment"
  command = "gcloud beta compute --project \"topher-dev-env\" ssh --zone \"us-west1-a\" \"dev-env\""
  output = ""

[[snippets]]
  description = "open dotfiles tmux window"
  command = "tmux new-window -c ~/dotfiles -n dotfiles -t 10 'git status && zsh'"
  output = ""

[[snippets]]
  description = "connect to new tmux session, creating it if it doesn't exist"
  command = "tmux new-sess -A -s work"
  output = ""

[[snippets]]
  description = "conda update environment packages"
  command = "conda env update --file ~/dev/memfault/environment.yml"
  output = ""

[[snippets]]
  description = "memfault gh pull request with stgit"
  command = "inv stg.pull-request"
  output = ""

[[snippets]]
  description = "swap keyboard config"
  command = "/usr/local/bin/keyboard"
  output = ""

[[snippets]]
  description = "start session memfault"
  command = "cd ~/dev/memfault && conda activate memfault"
  output = ""

[[snippets]]
  description = "open window for current directory"
  command = "nautilus . &"
  output = ""

[[snippets]]
  description = "upload android bugreport"
  command = "***REMOVED***"
  output = ""

[[snippets]]
  description = "run e2e test"
  command = "inv e2e.api --glob-pattern www/tests/e2e/test_chunks.py::test_chunks_compressed_heartbeat_event_upload"
  output = ""

[[snippets]]
  description = "rerun last command. upload stdout to gist and copy url to clipboard"
  command = "!! | gh gist create - | tee xsel"
  output = ""

[[snippets]]
  description = "connect to local docker memfault database"
  command = "PGPASSWORD=memfault psql -h localhost -p 5432 -U memfault memfault_db"
  output = ""

[[snippets]]
  description = "run black on changed modified files"
  command = "black $(git ls-files -m)"
  output = ""

[[snippets]]
  description = "create gist from clipboard TODO: tee creates a file, incorrect behavior"
  command = "xsel -o --clipboard | gh gist create - | tee xsel"
  output = ""

[[snippets]]
  description = "delete git branches which are deleted on remote"
  command = "git fetch -p && git branch -vv | awk '/: gone]/{print $1}' | vipe | xargs git branch -D"
  output = ""

[[snippets]]
  description = "resolve kitty ssh error on previous command. 'unknown terminal'"
  command = "kitty +kitten ssh !!"
  output = ""

[[snippets]]
  description = "create pull request"
  command = "git push -u origin HEAD && gh pr create --fill --draft"
  output = ""
