[[snippets]]
  description = "open vim file with fzf"
  command = "vim -o `fzf`"
  output = ""

[[snippets]]
  description = "sig kill emacs"
  command = "pkill -SIGUSR2 Emacs"
  output = ""

[[snippets]]
  description = "what's my ip"
  command = "curl v4.ifconfig.co | tee >(xsel)"
  output = ""

[[snippets]]
  description = "find from root"
  command = "find / -name \"*FIX_ME*\" 2>/dev/null"
  output = ""

[[snippets]]
  description = "copy last command"
  command = "echo \"\"\"!!\"\"\" | tee >(xsel -b)"
  output = ""

[[snippets]]
  description = "clear git rerere cache"
  command = "rm -rf .git/rr-cache"
  output = ""

[[snippets]]
  description = "kill all tmux sessions"
  command = "tmux list-sessions | cut -d: -f 1 | xargs -I {} tmux kill-session -t {}"
  output = ""

[[snippets]]
  description = "git filename changes since last commit"
  command = "git --no-pager diff --name-only HEAD^"
  output = ""

[[snippets]]
  description = "tmux kill unattached sessions"
  command = "tmux list-sessions | grep -v attached | cut -d: -f 1 | xargs -I {} tmux kill-session -t {}"
  output = ""

[[snippets]]
  description = "list directories and their sizes, sorted and human readable"
  command = "du -h | sort -h"
  output = ""

[[snippets]]
  description = "format json from the clipboard"
  command = "xsel -o | jq . | xsel"
  output = ""

[[snippets]]
  description = "python dictionary to json"
  command = "xsel | xargs -0 python -c 'import ast, json, sys ; out = ast.literal_eval(sys.argv[1]) ; print json.dumps(out)' | jq . | tee >(xsel)"
  output = ""

[[snippets]]
  description = "list users of port 8000"
  command = "lsof -nP -i4TCP:8000"
  output = ""

[[snippets]]
  description = "kill all running docker containers"
  command = "docker ps -q | xargs docker kill"
  output = ""

[[snippets]]
  description = "hg diff less with color"
  command = "hg d --color on | less"
  output = ""

[[snippets]]
  description = "open dotfiles tmux window"
  command = "tmux new-window -c ~/dotfiles -n dotfiles -t 10 'git status && zsh'"
  output = ""

[[snippets]]
  description = "connect to new tmux session, creating it if it doesn't exist"
  command = "tmux new-sess -A -s work"
  output = ""

[[snippets]]
  description = "conda update environment packages"
  command = "conda env update --file ~/dev/memfault/environment.yml"
  output = ""

[[snippets]]
  description = "memfault gh pull request with stgit"
  command = "inv stg.pull-request"
  output = ""

[[snippets]]
  description = "swap keyboard config"
  command = "/usr/local/bin/keyboard"
  output = ""

[[snippets]]
  description = "start session memfault"
  command = "cd ~/dev/memfault && conda activate memfault"
  output = ""

[[snippets]]
  description = "open window for current directory"
  command = "nautilus . &"
  output = ""

[[snippets]]
  description = "rerun last command. upload stdout to gist and copy url to clipboard"
  command = "!! | gh gist create - | tee >(xsel)"
  output = ""

[[snippets]]
  description = "run black on changed modified files"
  command = "black $(git ls-files -m)"
  output = ""

[[snippets]]
  description = "create gist from clipboard"
  command = "xsel -o | gh gist create - | tee >(xsel)"
  output = ""

[[snippets]]
  description = "delete git branches which are deleted on remote"
  command = "git fetch -p && git branch -vv | awk '/: gone]/{print $1}' | vipe | xargs git branch -D"
  output = ""

[[snippets]]
  description = "resolve kitty ssh error on previous command. 'unknown terminal'"
  command = "kitty +kitten ssh !!"
  output = ""

[[snippets]]
  description = "create pull request"
  command = "git push -u origin HEAD && gh pr create --fill --draft"
  output = ""

[[snippets]]
  description = "redis proxy to app.redsmin.com"
  command = "docker run -it --rm --name redsmin-proxy --network memfault_default -e REDSMIN_KEY=609056fb544e0c0f655afcdd -e REDIS_URI=\"redis://172.18.0.2:6379\" redsmin/proxy"
  output = ""

[[snippets]]
  description = "rdb connect to celery worker debug"
  command = "telnet localhost 6899 || telnet localhost 6900"
  output = ""

[[snippets]]
  description = "run the same 'ag' but looking for hidden files"
  command = "ag workflow_dis --hidden"
  output = ""

[[snippets]]
  description = "aws login root"
  command = "aws-vault login topher-root"
  output = ""

[[snippets]]
  description = "aws login prod"
  command = "aws-vault login topher-prod"
  output = ""

[[snippets]]
  description = "delete .tmp temp branches from git"
  command = "g b | grep \\\\.tmp | vipe | xargs git branch -D "
  output = ""

[[snippets]]
  description = "run rebase interactive stgit"
  command = "/home/topher/dev/stgit/contrib/stg-rebase-interactive"
  output = ""

[[snippets]]
  description = "start memfault servers in tmux panes"
  command = "tmuxp load work"
  output = ""

[[snippets]]
  description = "update python dependencies"
  command = "invoke poetry.lock poetry.export "
  output = ""
