---
name: Publish Docker image to Docker Hub
on:
  push:
    branches:
      - master
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx (aka BUILDKIT)
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: topher200/dotfiles:latest
          file: ./Dockerfile
          cache-from: type=registry,ref=topher200/dotfiles:buildcache
          cache-to: type=registry,ref=topher200/dotfiles:buildcache,mode=max
